import type { Metric } from './types';
import { safeDivide } from '../utils/math';

export const ARPU_METRIC: Metric = {
    id: 'arpu',
    name: 'Average Revenue Per User (ARPU)',
    iconName: 'Banknote',
    shortDescription: 'Revenue generated per active user',
    definition: 'ARPU measures the average amount of revenue generated by each active user or customer over a specific period. It is a vital measure of the continuous value generated by your user base.',
    whyItMatters: 'ARPU indicates the value of your customer base and your ability to upsell/cross-sell. Increasing ARPU is often more efficient than acquiring new customers.',
    formula: 'ARPU = Total Revenue ÷ Total Users',
    formulaPlain: 'ARPU equals total revenue divided by total number of active users',
    sampleCalculation: {
        description: 'Monthly Revenue is $50,000 and Total Users is 500',
        steps: [
            'Total Revenue: $50,000',
            'Total Users: 500',
            'ARPU = $50,000 ÷ 500 = $100'
        ]
    },
    supportsBusinessTypes: true,
    calculator: {
        inputs: [
            { name: 'revenue', label: 'Total Revenue (Monthly)', unit: '$', min: 0, max: 1000000, step: 1000, defaultValue: 50000, prefix: '$' },
            { name: 'users', label: 'Total Active Users', unit: 'users', min: 1, max: 100000, step: 1, defaultValue: 500 }
        ],
        calculateFn: (inputs) => safeDivide(inputs.revenue, inputs.users),
        formatResult: (result) => result === null ? 'N/A' : `$${result.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        getBenchmark: (result, businessType) => {
            if (result === null) return { threshold: 0, color: 'error', label: 'Cannot Calculate', feedback: 'Enter revenue and users to calculate ARPU.' };

            if (businessType === 'B2B') {
                if (result >= 1000) return { threshold: 1000, color: 'success', label: 'High (Enterprise)', feedback: 'Strong enterprise-level ARPU.' };
                if (result >= 100) return { threshold: 100, color: 'success', label: 'Good (Mid-Market)', feedback: 'Solid ARPU for B2B mid-market SaaS.' };
                if (result >= 20) return { threshold: 20, color: 'warning', label: 'SMB', feedback: 'Typical for lower-touch SMB SaaS.' };
                return { threshold: 0, color: 'warning', label: 'Low', feedback: 'Low ARPU for B2B. Ensure your CAC is very low to be sustainable.' };
            } else {
                // B2C
                if (result >= 50) return { threshold: 50, color: 'success', label: 'High', feedback: 'Excellent ARPU for a consumer product.' };
                if (result >= 10) return { threshold: 10, color: 'success', label: 'Good', feedback: 'Healthy consumer ARPU.' };
                if (result >= 2) return { threshold: 2, color: 'warning', label: 'Average', feedback: 'Standard for ad-supported or freemium consumer apps.' };
                return { threshold: 0, color: 'warning', label: 'Low', feedback: 'Very low ARPU. You need massive scale to succeed.' };
            }
        }
    },
    tips: [
        'Segment ARPU by customer type (e.g., SMB vs Enterprise) for deeper insights',
        'Track ARPU alongside Churn - high ARPU customers are worth fighting to keep',
        'Raise ARPU through add-ons, tiered pricing, and seat expansion',
        'Don\'t confuse ARPU with LTV (Lifetime Value)'
    ],
    commonMistakes: [
        'Including free trial users in the denominator (dilutes ARPU)',
        'Mixing monthly and annual revenue figures',
        'Ignoring non-recurring revenue if primarily tracking subscription health',
        'Comparing ARPU across completely different business models (e.g. ads vs subs)'
    ],
    hasChart: true,
    chartType: 'line'
};
